export interface LanguageOption {
  code: string;
  name: string; // e.g. English, हिन्दी, தமிழ்
  nativeName: string;
}

export const INDIAN_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' }
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    brand: 'Chronova',
    tagline: 'Campus Events, Study Hub & Student Clubs',
    events: 'Events',
    studyHub: 'Study Hub',
    clubs: 'Club Directory',
    qrHub: 'QR Passes',
    feedback: 'Feedback',
    login: 'Log In',
    signup: 'Sign Up',
    logout: 'Log Out',
    myVault: 'My Vault',
    studentPanel: 'Student',
    adminPanel: 'Admin',
    searchPlaceholder: 'Search events, notes, clubs...',
    joinClub: 'Join Club',
    joined: 'Joined',
    checkIn: 'Check In',
    checkedIn: 'Checked In',
    members: 'Members',
    lead: 'Lead',
    meeting: 'Meeting',
    location: 'Location',
    upcomingEvents: 'Upcoming Events',
    academicNotes: 'Academic Resources',
    activeClubs: 'Active Student Clubs',
    viewDetails: 'View Details',
    registerNow: 'Register Now',
    downloadNotes: 'Download Notes',
    welcomeBack: 'Welcome back',
    selectRolePrompt: 'Select your portal role to continue',
    themeLight: 'Light Mode',
    themeDark: 'Dark Mode',
    allDepartments: 'All Departments',
    filterBy: 'Filter'
  },
  hi: {
    brand: 'क्रोनोवा',
    tagline: 'कैंपस इवेंट्स, स्टडी हब और छात्र क्लब',
    events: 'इवेंट्स',
    studyHub: 'स्टडी हब',
    clubs: 'क्लब डायरेक्टरी',
    qrHub: 'क्यूआर पास',
    feedback: 'फीडबैक',
    login: 'लॉग इन',
    signup: 'साइन अप',
    logout: 'लॉग आउट',
    myVault: 'माई वॉल्ट',
    studentPanel: 'विद्यार्थी',
    adminPanel: 'व्यवस्थापक',
    searchPlaceholder: 'इवेंट्स, नोट्स, क्लब खोजें...',
    joinClub: 'क्लब से जुड़ें',
    joined: 'जुड़े हुए',
    checkIn: 'चेक इन',
    checkedIn: 'चेक इन हुआ',
    members: 'सदस्य',
    lead: 'अध्यक्ष',
    meeting: 'बैठक',
    location: 'स्थान',
    upcomingEvents: 'आगामी कार्यक्रम',
    academicNotes: 'अध्ययन सामग्री',
    activeClubs: 'सक्रिय छात्र क्लब',
    viewDetails: 'विवरण देखें',
    registerNow: 'अभी रजिस्टर करें',
    downloadNotes: 'नोट्स डाउनलोड करें',
    welcomeBack: 'पुनः स्वागत है',
    selectRolePrompt: 'जारी रखने के लिए अपना पोर्टल रोल चुनें',
    themeLight: 'लाइट मोड',
    themeDark: 'डार्क मोड',
    allDepartments: 'सभी विभाग',
    filterBy: 'फ़िल्टर'
  },
  bn: {
    brand: 'ক্রোনোভা',
    tagline: 'ক্যাম্পাস ইভেন্ট, স্টাডি হাব ও ক্লাব',
    events: 'ইভেন্ট',
    studyHub: 'স্টাডি হাব',
    clubs: 'ক্লাব ডিরেক্টরি',
    qrHub: 'কিউআর পাস',
    feedback: 'মতামত',
    login: 'লগ ইন',
    signup: 'সাইন আপ',
    logout: 'লগ আউট',
    myVault: 'মাই ভল্ট',
    studentPanel: 'শিক্ষার্থী',
    adminPanel: 'এডমিন',
    searchPlaceholder: 'ইভেন্ট, নোট, ক্লাব খুঁজুন...',
    joinClub: 'ক্লাবে যুক্ত হোন',
    joined: 'যুক্ত আছেন',
    checkIn: 'চেক ইন',
    checkedIn: 'চেক ইন সম্পন্ন',
    members: 'সদস্য',
    lead: 'প্রধান',
    meeting: 'মিটিং',
    location: 'স্থান',
    upcomingEvents: 'আসন্ন ইভেন্ট',
    academicNotes: 'পড়াশোনার উপাদান',
    activeClubs: 'সক্রিয় ছাত্র ক্লাব',
    viewDetails: 'বিস্তারিত দেখুন',
    registerNow: 'রেজিস্ট্রেশন করুন',
    downloadNotes: 'নোট ডাউনলোড',
    welcomeBack: 'স্বাগতম',
    selectRolePrompt: 'পোর্টাল নির্বাচন করুন',
    themeLight: 'লাইট মোড',
    themeDark: 'ডার্ক মোড',
    allDepartments: 'সব বিভাগ',
    filterBy: 'ফিল্টার'
  },
  te: {
    brand: 'క్రోనోవా',
    tagline: 'క్యాంపస్ ఈవెంట్లు, స్టడీ హబ్ మరియు క్లబ్‌లు',
    events: 'ఈవెంట్లు',
    studyHub: 'స్టడీ హబ్',
    clubs: 'క్లబ్ డైరెక్టరీ',
    qrHub: 'QR పాస్‌లు',
    feedback: 'ఫీడ్‌బ్యాక్',
    login: 'లాగిన్',
    signup: 'సైన్ అప్',
    logout: 'లాగ్ అవుట్',
    myVault: 'నా వాల్ట్',
    studentPanel: 'విద్యార్థి',
    adminPanel: 'అడ్మిన్',
    searchPlaceholder: 'ఈవెంట్లు, నోట్స్, క్లబ్‌లను వెతకండి...',
    joinClub: 'క్లబ్‌లో చేరండి',
    joined: 'చేరారు',
    checkIn: 'చెక్-ఇన్',
    checkedIn: 'చెక్-ఇన్ అయింది',
    members: 'సభ్యులు',
    lead: 'లీడ్',
    meeting: 'సమావేశం',
    location: 'ప్రదేశం',
    upcomingEvents: 'రాబోయే ఈవెంట్లు',
    academicNotes: 'స్టడీ మెటీరియల్',
    activeClubs: 'విద్యార్థి క్లబ్‌లు',
    viewDetails: 'వివరాలు చూడండి',
    registerNow: 'నమోదు చేసుకోండి',
    downloadNotes: 'నోట్స్ డౌన్‌లోడ్',
    welcomeBack: 'స్వాగతం',
    selectRolePrompt: 'కొనసాగడానికి రోల్ ఎంచుకోండి',
    themeLight: 'లైట్ మోడ్',
    themeDark: 'డార్క్ మోడ్',
    allDepartments: 'అన్ని విభాగాలు',
    filterBy: 'ఫిల్టర్'
  },
  mr: {
    brand: 'क्रोनोव्हा',
    tagline: 'कॅम्पस इव्हेंट्स, स्टडी हब आणि क्लब्स',
    events: 'इव्हेंट्स',
    studyHub: 'स्टडी हब',
    clubs: 'क्लब डायरेक्टरी',
    qrHub: 'QR पासेस',
    feedback: 'अभिप्राय',
    login: 'लॉग इन',
    signup: 'साइन अप',
    logout: 'लॉग आउट',
    myVault: 'माय व्हॉल्ट',
    studentPanel: 'विद्यार्थी',
    adminPanel: 'अॅडमिन',
    searchPlaceholder: 'इव्हेंट्स, नोट्स, क्लब शोधा...',
    joinClub: 'क्लबमध्ये सामील व्हा',
    joined: 'सामील झाले',
    checkIn: 'चेक इन',
    checkedIn: 'चेक इन पूर्ण',
    members: 'सदस्य',
    lead: 'प्रमुख',
    meeting: 'बैठक',
    location: 'स्थान',
    upcomingEvents: 'आगामी इव्हेंट्स',
    academicNotes: 'अभ्यास साहित्य',
    activeClubs: 'सक्रिय क्लब्स',
    viewDetails: 'तपशील पहा',
    registerNow: 'आता नोंदणी करा',
    downloadNotes: 'नोट्स डाउनलोड करा',
    welcomeBack: 'पुन्हा स्वागत आहे',
    selectRolePrompt: 'कृपया तुमची भूमिका निवडा',
    themeLight: 'लाइट मोड',
    themeDark: 'डार्क मोड',
    allDepartments: 'सर्व विभाग',
    filterBy: 'फिल्टर'
  },
  ta: {
    brand: 'குரோனோவா',
    tagline: 'வளாக நிகழ்வுகள், படிப்பு மையம் மற்றும் மன்றங்கள்',
    events: 'நிகழ்வுகள்',
    studyHub: 'படிப்பு மையம்',
    clubs: 'மன்றங்கள்',
    qrHub: 'QR அனுமதிச்சீட்டு',
    feedback: 'கருத்துகள்',
    login: 'உள்நுழைக',
    signup: 'பதிவு செய்க',
    logout: 'வெளியேறுக',
    myVault: 'எனது சேமிப்பு',
    studentPanel: 'மாணவர்',
    adminPanel: 'நிர்வாகம்',
    searchPlaceholder: 'நிகழ்வுகள், குறிப்புகள் தேடுக...',
    joinClub: 'மன்றத்தில் இணைக',
    joined: 'இணைந்தார்',
    checkIn: 'வருகை பதிவு',
    checkedIn: 'பதிவு செய்யப்பட்டது',
    members: 'உறுப்பினர்கள்',
    lead: 'தலைவர்',
    meeting: 'கூட்டம்',
    location: 'இடம்',
    upcomingEvents: 'வரவிருக்கும் நிகழ்வுகள்',
    academicNotes: 'கல்வி குறிப்புகள்',
    activeClubs: 'மாணவர் மன்றங்கள்',
    viewDetails: 'விவரங்களை பார்க்க',
    registerNow: 'இப்போதே பதிவு செய்',
    downloadNotes: 'பதிவிறக்குக',
    welcomeBack: 'மீண்டும் நல்வரவு',
    selectRolePrompt: 'தொடர உங்கள் பங்கைத் தேர்ந்தெடுக்கவும்',
    themeLight: 'ஒளி பயன்முறை',
    themeDark: 'இருள் பயன்முறை',
    allDepartments: 'அனைத்து துறைகள்',
    filterBy: 'வடிகட்டி'
  },
  gu: {
    brand: 'ક્રોનોવા',
    tagline: 'કેમ્પસ ઇવેન્ટ્સ, સ્ટડી હબ અને ક્લબ્સ',
    events: 'ઇવેન્ટ્સ',
    studyHub: 'સ્ટડી હબ',
    clubs: 'ક્લબ ડિરેક્ટરી',
    qrHub: 'QR પાસ',
    feedback: 'પ્રતિસાદ',
    login: 'લૉગ ઇન',
    signup: 'સાઇન અપ',
    logout: 'લૉગ આઉટ',
    myVault: 'માય વોલ્ટ',
    studentPanel: 'વિદ્યાર્થી',
    adminPanel: 'એડમિન',
    searchPlaceholder: 'ઇવેન્ટ્સ, નોટ્સ, ક્લબ શોધો...',
    joinClub: 'ક્લબમાં જોડાઓ',
    joined: 'જોડાયેલ',
    checkIn: 'ચેક ઇન',
    checkedIn: 'ચેક ઇન થયું',
    members: 'સભ્યો',
    lead: 'લીડ',
    meeting: 'મીટિંગ',
    location: 'સ્થળ',
    upcomingEvents: 'આગામી ઇવેન્ટ્સ',
    academicNotes: 'અભ્યાસ સામગ્રી',
    activeClubs: 'સક્રિય ક્લબ્સ',
    viewDetails: 'વિગતો જુઓ',
    registerNow: 'હમણાં નોંધણી કરો',
    downloadNotes: 'નોટ્સ ડાઉનલોડ',
    welcomeBack: 'સ્વાગત છે',
    selectRolePrompt: 'ચાલુ રાખવા માટે તમારી ભૂમિકા પસંદ કરો',
    themeLight: 'લાઇટ મોડ',
    themeDark: 'ડાર્ક મોડ',
    allDepartments: 'બધા વિભાગો',
    filterBy: 'ફિલ્ટર'
  },
  kn: {
    brand: 'ಕ್ರೋನೋವಾ',
    tagline: 'ಕ್ಯಾಂಪಸ್ ಕಾರ್ಯಕ್ರಮಗಳು, ಅಧ್ಯಯನ ಕೇಂದ್ರ ಮತ್ತು ಕ್ಲಬ್‌ಗಳು',
    events: 'ಕಾರ್ಯಕ್ರಮಗಳು',
    studyHub: 'ಸ್ಟಡಿ ಹಬ್',
    clubs: 'ಕ್ಲಬ್ ಡೈರೆಕ್ಟರಿ',
    qrHub: 'QR ಪಾಸ್‌ಗಳು',
    feedback: 'ಪ್ರತಿಕ್ರಿಯೆ',
    login: 'ಲಾಗಿನ್',
    signup: 'ಸೈನ್ ಅಪ್',
    logout: 'ಲಾಗ್ ಔಟ್',
    myVault: 'ಮೈ ವಾಲ್ಟ್',
    studentPanel: 'ವಿದ್ಯಾರ್ಥಿ',
    adminPanel: 'ನಿರ್ವಾಹಕ',
    searchPlaceholder: 'ಕಾರ್ಯಕ್ರಮಗಳು, ನೋಟ್ಸ್‌ ಹುಡುಕಿ...',
    joinClub: 'ಕ್ಲಬ್ ಸೇರಿ',
    joined: 'ಸೇರಲಾಗಿದೆ',
    checkIn: 'ಚೆಕ್ ಇನ್',
    checkedIn: 'ಚೆಕ್ ಇನ್ ಆಗಿದೆ',
    members: 'ಸದಸ್ಯರು',
    lead: 'ನಾಯಕ',
    meeting: 'ಸಭೆ',
    location: 'ಸ್ಥಳ',
    upcomingEvents: 'ಮುಂಬರುವ ಕಾರ್ಯಕ್ರಮಗಳು',
    academicNotes: 'ಅಧ್ಯಯನ ಟಿಪ್ಪಣಿಗಳು',
    activeClubs: 'ವಿದ್ಯಾರ್ಥಿ ಕ್ಲಬ್‌ಗಳು',
    viewDetails: 'ವಿವರ ನೋಡಿ',
    registerNow: 'ಈಗಲೇ ನೋಂದಾಯಿಸಿ',
    downloadNotes: 'ನೋಟ್ಸ್ ಡೌನ್‌ಲೋಡ್',
    welcomeBack: 'ಸುಸ್ವಾಗತ',
    selectRolePrompt: 'ಮುಂದುವರಿಯಲು ಪಾತ್ರ ಆಯ್ಕೆಮಾಡಿ',
    themeLight: 'ಲೈಟ್ ಮೋಡ್',
    themeDark: 'ಡಾರ್ಕ್ ಮೋಡ್',
    allDepartments: 'ಎಲ್ಲಾ ವಿಭಾಗಗಳು',
    filterBy: 'ಫಿಲ್ಟರ್'
  },
  pa: {
    brand: 'ਕ੍ਰੋਨੋਵਾ',
    tagline: 'ਕੈਂਪਸ ਈਵੈਂਟਸ, ਸਟੱਡੀ ਹੱਬ ਅਤੇ ਕਲੱਬ',
    events: 'ਈਵੈਂਟਸ',
    studyHub: 'ਸਟੱਡੀ ਹੱਬ',
    clubs: 'ਕਲੱਬ ਡਾਇਰੈਕਟਰੀ',
    qrHub: 'QR ਪਾਸ',
    feedback: 'ਫੀਡਬੈਕ',
    login: 'ਲਾਗ ਇਨ',
    signup: 'ਸਾਈਨ ਅੱਪ',
    logout: 'ਲਾਗ ਆਉਟ',
    myVault: 'ਮਾਈ ਵਾਲਟ',
    studentPanel: 'ਵਿਦਿਆਰਥੀ',
    adminPanel: 'ਐਡਮਿਨ',
    searchPlaceholder: 'ਈਵੈਂਟਸ, ਨੋਟਸ, ਕਲੱਬ ਲੱਭੋ...',
    joinClub: 'ਕਲੱਬ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ',
    joined: 'ਸ਼ਾਮਲ ਹੋਏ',
    checkIn: 'ਚੈੱਕ ਇਨ',
    checkedIn: 'ਚੈੱਕ ਇਨ ਹੋ ਗਿਆ',
    members: 'ਮੈਂਬਰ',
    lead: 'ਮੋਢੀ',
    meeting: 'ਮੀਟਿੰਗ',
    location: 'ਸਥਾਨ',
    upcomingEvents: 'ਆਉਣ ਵਾਲੇ ਸਮਾਗਮ',
    academicNotes: 'ਅਧਿਐਨ ਸਮੱਗਰੀ',
    activeClubs: 'ਕਿਰਿਆਸ਼ੀਲ ਕਲੱਬ',
    viewDetails: 'ਵੇਰਵੇ ਵੇਖੋ',
    registerNow: 'ਹੁਣੇ ਰਜਿਸਟਰ ਕਰੋ',
    downloadNotes: 'ਨੋਟਸ ਡਾਊਨਲੋਡ ਕਰੋ',
    welcomeBack: 'ਜੀ ਆਇਆਂ ਨੂੰ',
    selectRolePrompt: 'ਜਾਰੀ ਰੱਖਣ ਲਈ ਰੋਲ ਚੁਣੋ',
    themeLight: 'ਲਾਈਟ ਮੋਡ',
    themeDark: 'ਡਾਰਕ ਮੋਡ',
    allDepartments: 'ਸਾਰੇ ਵਿਭਾਗ',
    filterBy: 'ਫਿਲਟਰ'
  },
  ml: {
    brand: 'ക്രോണോവ',
    tagline: 'ക്യാമ്പസ് ഇവന്റുകൾ, സ്റ്റഡി ഹബ്ബ് & ക്ലബ്ബുകൾ',
    events: 'ഇവന്റുകൾ',
    studyHub: 'സ്റ്റഡി ഹബ്ബ്',
    clubs: 'ക്ലബ്ബ് ഡയറക്ടറി',
    qrHub: 'QR പാസുകൾ',
    feedback: 'അഭിപ്രായം',
    login: 'ലോഗിൻ',
    signup: 'സൈൻ അപ്പ്',
    logout: 'ലോഗ് ഔട്ട്',
    myVault: 'മൈ വോൾട്ട്',
    studentPanel: 'വിദ്യാർത്ഥി',
    adminPanel: 'അഡ്മിൻ',
    searchPlaceholder: 'ഇവന്റുകൾ, കുറിപ്പുകൾ തിരയുക...',
    joinClub: 'ക്ലബ്ബിൽ ചേരുക',
    joined: 'ചേർന്നു',
    checkIn: 'ചെക്ക് ഇൻ',
    checkedIn: 'ചെക്ക് ഇൻ ചെയ്തു',
    members: 'അംഗങ്ങൾ',
    lead: 'ലീഡ്',
    meeting: 'യോഗം',
    location: 'സ്ഥലം',
    upcomingEvents: 'വരാനിരിക്കുന്ന ഇവന്റുകൾ',
    academicNotes: 'പഠന സാമഗ്രികൾ',
    activeClubs: 'ക്ലബ്ബുകൾ',
    viewDetails: 'വിശദാംശങ്ങൾ കാണുക',
    registerNow: 'ഇപ്പോൾ രജിസ്റ്റർ ചെയ്യുക',
    downloadNotes: 'ഡൗൺലോഡ് കുറിപ്പുകൾ',
    welcomeBack: 'സ്വാഗതം',
    selectRolePrompt: 'തുടരാൻ നിങ്ങളുടെ റോൾ തിരഞ്ഞെടുക്കുക',
    themeLight: 'ലൈറ്റ് മോഡ്',
    themeDark: 'ഡാർക്ക് മോഡ്',
    allDepartments: 'എല്ലാ വിഭാഗങ്ങളും',
    filterBy: 'ഫിൽട്ടർ'
  }
};
